# Generated by Django 5.2.17 on 2026-09-28 21:35

import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0004_alter_movie_options_movie_active_movie_artwork_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='优惠码')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('percent', models.PositiveIntegerField(default=10, verbose_name='租金折扣百分比')),
                ('active', models.BooleanField(default=True, verbose_name='有效')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='到期时间')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('percent__gte', 1), ('percent__lte', 100)), name='valid_discount_percent')],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='姓名')),
                ('phone', models.CharField(max_length=30, unique=True, verbose_name='电话')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('active', models.BooleanField(default=True, verbose_name='有效')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('points', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerCoupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rentals.coupon')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coupons', to='rentals.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('recharge', '模拟充值'), ('refund', '退还余额'), ('rental', '租借扣款')], max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('request_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger', to='rentals.customer')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_at', models.DateTimeField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('request_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to='rentals.customer')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RentalItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('returned_quantity', models.PositiveIntegerField(default=0)),
                ('lost_quantity', models.PositiveIntegerField(default=0)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rental_items', to='movies.movie')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='rentals.rental')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('rental_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lost_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', '模拟现金'), ('balance', '余额')], max_length=10)),
                ('request_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('coupon', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rentals.customercoupon')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='rentals.rental')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('lost_quantity', models.PositiveIntegerField(default=0)),
                ('days', models.PositiveIntegerField()),
                ('charged_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rental_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rentals.rentalitem')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='rentals.returnrecord')),
            ],
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='nonnegative_balance'),
        ),
        migrations.AddConstraint(
            model_name='customercoupon',
            constraint=models.UniqueConstraint(fields=('customer', 'coupon'), name='one_coupon_per_customer'),
        ),
        migrations.AddConstraint(
            model_name='rentalitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='positive_rental_quantity'),
        ),
        migrations.AddConstraint(
            model_name='rentalitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', django.db.models.expressions.CombinedExpression(models.F('returned_quantity'), '+', models.F('lost_quantity')))), name='settled_not_above_rented'),
        ),
    ]
