# Generated by Django 5.2.17 on 2026-09-29 19:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_options_movie_active_movie_artwork_and_more'),
        ('rentals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieWish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='想看的电影')),
                ('release_year', models.PositiveIntegerField(verbose_name='上映年份')),
                ('normalized_key', models.CharField(editable=False, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('requested', '待评估'), ('planned', '采购中'), ('available', '已到货'), ('declined', '暂不采购')], default='requested', max_length=12)),
                ('manager_note', models.CharField(blank=True, max_length=500, verbose_name='处理说明')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='movies.movie')),
            ],
        ),
        migrations.CreateModel(
            name='PointsEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField()),
                ('points_after', models.PositiveIntegerField()),
                ('note', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='points_entries', to='rentals.customer')),
                ('ledger', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='rentals.ledger')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PolicyRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('received_quantity', models.PositiveIntegerField(default=0)),
                ('supplier', models.CharField(blank=True, max_length=120)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('request_key', models.UUIDField(unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='movies.movie')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('wish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='rentals.moviewish')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RewardPolicy',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('money_unit', models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='每多少欧元')),
                ('points_unit', models.PositiveIntegerField(default=10, verbose_name='赠送多少积分')),
                ('enabled', models.BooleanField(default=True, verbose_name='开启顾客模拟充值')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('request_key', models.UUIDField(unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='rentals.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='TopUp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_key', models.UUIDField(unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('money_unit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('points_unit', models.PositiveIntegerField()),
                ('awarded_points', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', '待支付'), ('success', '支付成功'), ('failed', '支付失败'), ('cancelled', '已取消'), ('expired', '已过期')], default='pending', max_length=12)),
                ('provider_reference', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reversed_points', models.PositiveIntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topups', to='rentals.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WishRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='补充信息')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wishes', to='rentals.customer')),
                ('wish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='rentals.moviewish')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0), ('received_quantity__lte', models.F('quantity'))), name='purchase_quantity_range'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__gte', 0)), name='purchase_cost_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='rewardpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('id', 1)), name='singleton_reward_policy'),
        ),
        migrations.AddConstraint(
            model_name='rewardpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('money_unit__gte', Decimal('0.01')), ('money_unit__lte', 10000)), name='reward_money_range'),
        ),
        migrations.AddConstraint(
            model_name='rewardpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('points_unit__gte', 1), ('points_unit__lte', 10000)), name='reward_points_range'),
        ),
        migrations.AddConstraint(
            model_name='topup',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 1), ('amount__lte', 10000)), name='topup_amount_range'),
        ),
        migrations.AddConstraint(
            model_name='topup',
            constraint=models.CheckConstraint(condition=models.Q(('refunded_amount__lte', models.F('amount'))), name='topup_refund_cap'),
        ),
        migrations.AddConstraint(
            model_name='wishrequest',
            constraint=models.UniqueConstraint(fields=('customer', 'wish'), name='one_wish_per_customer'),
        ),
    ]
