# Generated by Django 5.2.17 on 2026-09-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_moviewish_pointsentry_policyrevision_purchaseorder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=30, unique=True, verbose_name='Coupon code'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expires at'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='percent',
            field=models.PositiveIntegerField(default=10, verbose_name='Rental discount (%)'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=30, unique=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='kind',
            field=models.CharField(choices=[('recharge', 'Simulated top-up'), ('refund', 'Balance refund'), ('rental', 'Rental payment')], max_length=12),
        ),
        migrations.AlterField(
            model_name='moviewish',
            name='manager_note',
            field=models.CharField(blank=True, max_length=500, verbose_name='Manager update'),
        ),
        migrations.AlterField(
            model_name='moviewish',
            name='release_year',
            field=models.PositiveIntegerField(verbose_name='Release year'),
        ),
        migrations.AlterField(
            model_name='moviewish',
            name='status',
            field=models.CharField(choices=[('requested', 'Under review'), ('planned', 'On order'), ('available', 'Arrived'), ('declined', 'Not planned')], default='requested', max_length=12),
        ),
        migrations.AlterField(
            model_name='moviewish',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Requested movie'),
        ),
        migrations.AlterField(
            model_name='returnrecord',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Simulated cash'), ('balance', 'Balance')], max_length=10),
        ),
        migrations.AlterField(
            model_name='rewardpolicy',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Enable customer simulated top-ups'),
        ),
        migrations.AlterField(
            model_name='rewardpolicy',
            name='money_unit',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='For every EUR'),
        ),
        migrations.AlterField(
            model_name='rewardpolicy',
            name='points_unit',
            field=models.PositiveIntegerField(default=10, verbose_name='Award this many points'),
        ),
        migrations.AlterField(
            model_name='topup',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending payment'), ('success', 'Payment successful'), ('failed', 'Payment failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=12),
        ),
        migrations.AlterField(
            model_name='wishrequest',
            name='note',
            field=models.CharField(blank=True, max_length=500, verbose_name='Additional information'),
        ),
    ]
