# Generated by Django 2.1 on 2026-09-23 22:32

import datetime
from django.db import migrations, models
utc = datetime.timezone.utc


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 23, 22, 32, 40, 557827, tzinfo=utc)),
        ),
    ]
