# Generated by Django 5.2.17 on 2026-09-30 14:54

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_options_movie_active_movie_artwork_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Listed'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='barcode',
            field=models.CharField(max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Enter exactly 10 digits.')], verbose_name='10-digit barcode'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Daily rate'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(blank=True, max_length=120, verbose_name='Director'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movies.genre', verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='number_in_stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Available stock'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_year',
            field=models.IntegerField(verbose_name='Release year'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='runtime',
            field=models.PositiveIntegerField(default=120, verbose_name='Runtime (minutes)'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='synopsis',
            field=models.TextField(blank=True, verbose_name='Synopsis'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='total_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Total stock'),
        ),
    ]
