# Generated by Django 5.2.17 on 2026-09-28 21:35

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def initialize_stock(apps, schema_editor):
    Movie = apps.get_model('movies', 'Movie')
    for movie in Movie.objects.all():
        movie.total_quantity = movie.number_in_stock
        movie.barcode = str(1000000000 + movie.pk)
        movie.save(update_fields=['total_quantity', 'barcode'])


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20260923_2233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='movie',
            name='active',
            field=models.BooleanField(default=True, verbose_name='上架'),
        ),
        migrations.AddField(
            model_name='movie',
            name='artwork',
            field=models.CharField(default='orbit', max_length=40),
        ),
        migrations.AddField(
            model_name='movie',
            name='barcode',
            field=models.CharField(max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', '请输入 10 位数字')], verbose_name='10 位条码'),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(blank=True, max_length=120, verbose_name='导演'),
        ),
        migrations.AddField(
            model_name='movie',
            name='runtime',
            field=models.PositiveIntegerField(default=120, verbose_name='时长（分钟）'),
        ),
        migrations.AddField(
            model_name='movie',
            name='synopsis',
            field=models.TextField(blank=True, verbose_name='简介'),
        ),
        migrations.AddField(
            model_name='movie',
            name='total_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='总库存'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='日租金'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movies.genre', verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='number_in_stock',
            field=models.PositiveIntegerField(default=0, verbose_name='可租库存'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_year',
            field=models.IntegerField(verbose_name='上映年份'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=255, verbose_name='片名'),
        ),
        migrations.RunPython(initialize_stock, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='movie',
            constraint=models.CheckConstraint(condition=models.Q(('number_in_stock__lte', models.F('total_quantity'))), name='stock_not_above_total'),
        ),
        migrations.AddConstraint(
            model_name='movie',
            constraint=models.CheckConstraint(condition=models.Q(('daily_rate__gt', 0)), name='positive_daily_rate'),
        ),
    ]
