-- CASE 1---
-- SESSION 1
USE sql_store;
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;
START TRANSACTION;
SELECT points FROM customers WHERE customer_id = 1;
SELECT points FROM customers WHERE customer_id = 1;
COMMIT;

-- SESSION 2
USE sql_store;
START TRANSACTION;
UPDATE customers
SET points = 40 -- 20/30
WHERE customer_id = 1;
COMMIT;

-- CASE 2---
-- SESSION 1
USE sql_store;
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;
START TRANSACTION;
SELECT * FROM customers WHERE state = 'VA';
COMMIT;

-- SESSION 2
USE sql_store;
START TRANSACTION;
UPDATE customers
SET state = 'VA' 
WHERE customer_id = 1;
COMMIT;