-- SESSION 1
USE sql_store;
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
START TRANSACTION;
SELECT * FROM customers WHERE state = 'VA';
COMMIT;

-- SESSION 2
USE sql_store;
START TRANSACTION;
UPDATE customers
SET State = 'VA'
WHERE customer_id = 3;
COMMIT;